practiceD/ecommerce/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from products.views import home, detail, search
from cart.views import view, cart_update
from order.views import checkout, Orders
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^cart/(?P<slug>[\w-]+)/$', cart_update, name='cart_update'),
    url(r'^cart/', view, name='view'),
    url(r'^s/$', search, name='searchproduct'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^orders/$', Orders, name='orders'),
    url(r'^(?P<slug>[\w-]+)/$', detail, name='details'),
    
        
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

practiceD/ecommerce/products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
import os
from django.utils.safestring import mark_safe

# Create your models here.
class product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=False)
    price = models.DecimalField(decimal_places=2, max_digits=10, default=19.99)
    slug = models.SlugField(unique = True)
    #Image = models.FileField(upload_to='products/images/', null= True)   
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

class productImage(models.Model):
    Product = models.ForeignKey(product)
    image = models.ImageField(upload_to='products/images/', blank=True)
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.Product.title

practiceD/ecommerce/products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import product, productImage
from django.shortcuts import render, Http404, HttpResponse

# Create your views here.
def home(request):
    products = product.objects.all()
    context = {
        'products': products 
    }
    return render(request, 'products/home.html',context)


def search(request):
    q = request.GET.get('Keyword')
    #return HttpResponse(q)
    products = product.objects.filter(title__icontains=q)
    #print products
    #return HttpResponse(products)
    if products:
        context = {"products": products, "query": q}
    else:
        message = "Somethings wents wrong! please try something new"
        context = {"empty": True, 'message': message, "query": q}
    return render(request, 'products/result.html', context)


def detail(request, slug):
    #try:
        details = product.objects.get(slug=slug)
        context = {
            'details': details
        }
        return render(request, 'products/detail.html', context)
#except:
    #    raise Http404

practiceD/ecommerce/templates/products/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    {% load staticfiles %}
    <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}' />
    <link rel="stylesheet" href='{% static "css/homepage.css" %}' />
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 	integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" 		crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 		integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" 		crossorigin="anonymous"></script>

    <title>Ecommerce</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">
  </head>

  <body class="bg-light">

    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
      <a class="navbar-brand mr-auto mr-lg-0" href="{% url 'home'%}">Ecommerce</a>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Notifications</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Switch account</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" role="search" action="/s/">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" name="Keyword" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        
      </div>
    </nav>

    <div class="nav-scroller bg-white shadow-sm">
        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <p><a href="#" class="btn btn-primary" role="button">Quantity</a> <a href="{% url 'view' %}" class="btn btn-primary" role="button">Add to Cart</a></p>
              </li>
          </ul>
        </div>
    </div>

    <main role="main" class="container">
      <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <p><a href="#" class="btn btn-primary" role="button">Quantity</a>&nbsp; <a href="#" class="btn btn-primary" role="button">Quantity</a> &nbsp;<a href="#" class="btn btn-primary" role="button">Quantity</a> &nbsp;<a href="#" class="btn btn-primary" role="button">Quantity</a> &nbsp;<a href="#" class="btn btn-primary" role="button">Quantity</a> &nbsp;<a href="#" class="btn btn-primary" role="button">Quantity</a> &nbsp;<a href="#" class="btn btn-primary" role="button">Quantity</a> &nbsp;<a href="#" class="btn btn-primary" role="button">Quantity</a>&nbsp; <a href="#" class="btn btn-primary" role="button">Quantity</a>&nbsp; 
                    <a href="{% url 'view' %}" class="btn btn-primary" role="button">View Cart <span class="badge"><b>{% if not request.session.item_total %} 0 {% else %} {{ request.session.item_total }} {% endif %}</b></span></a></p>
              </li>
          </ul>
        </div>
      </div>

    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script src="offcanvas.js"></script>
  </body>

practiceD/ecommerce/templates/products/detail.html
{% include 'products/base.html' %}

<div class="container">
    <div class="jumbotron">
{% for item in details.productimage_set.all %}
    <img src="{{ MEDIA_URL }}{{ item.image }}" style="width:100%; height: 100%;">
{% endfor %}

<h1>Title: {{details.title}}</h1>
<h1>Description: {{details.description}}</h1>
<h1>Price: {{details.price}}</h1>
</div>

</div>

practiceD/ecommerce/templates/products/home.html
<html>

<head>
    {% load staticfiles %}
    <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}' />
    <link rel="stylesheet" href='{% static "css/homepage.css" %}' />
    <link rel="stylesheet" href='{% static "js/homepage.js" %}' />
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">


    
</head>
{% include 'products/base.html' %}

<!--<div class="container">
    <h1>hey {{username}} </h1>



<div class="row">    
    
{% for product in products %}    
   
    <div class="col-sm-4" style="background-color:lavender;"><br>
        {% for item in product.productimage_set.all %}
            <a href="{% url 'details' product.slug%}"><img src="{{ MEDIA_URL }}{{ item.image }}" style="width:350px; height: 250px;"><br/></a>
        {% endfor %}
            {{product.title }} {{ product.price}}<br>
    </div>
    
{% endfor %}
</div>

</div>
-->
<div class="container">
    <div class="page-header">{{ message }}</div>
<div class="row">
    {% for product in products %}
        
        <div class="col-md-4">
            <div class="thumbnail">
                {% for item in product.productimage_set.all %}
                    <a href="{% url 'details' product.slug%}"><img src="{{ MEDIA_URL }}{{ item.image }}" class="img-responsive" style="width:80%; height: 250px; margin: 10%;"></a>
                {% endfor %}
            <div class="caption">
              <h3>{{ product.title }}</h3>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a href="{% url 'details' product.slug %}" class="btn btn-primary col-sm-12 pull-left" style="float:left;" role="button">View</a> <form class="btn btn-primary col-sm-12 pull-left" style="float:left;" method="GET" action="{% url 'cart_update' product.slug %}"><input type="number" value="1" name="qty" min="0" max="1000" ><input class="btn btn-primary" type="submit" value="Add to Cart"></form></p>
            </div>
          </div>
    
</div><br>
{% endfor %}
</div>

practiceD/ecommerce/templates/products/result.html
{% include 'products/base.html' %}


<div class="container">
    <div class="page-header">
        <h1>You searched for: {{ query }}</h1>
    </div>

    {% if empty %}
    <hr>
    <h1>{{ message }}</h1>
    {% endif %}

    <hr>
    <div class="row">
            {% for product in products %}
                
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        {% for item in product.productimage_set.all %}
                            <a href="{% url 'details' product.slug%}"><img src="{{ MEDIA_URL }}{{ item.image }}" class="img-responsive" style="width:80%; height: 250px; margin: 10%;"></a>
                        {% endfor %}
                    <div class="caption">
                      <h3>{{ product.title }}</h3>
                      <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                      <p><a href="{% url 'details' product.slug %}" class="btn btn-primary" role="button">View</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
                    </div>
                  </div>
            
        </div><br>
        {% endfor %}          
</div>